Species.destroy_all

Species.create({name: "Unknown Species"})
Species.create({name: "Alder"})
Species.create({name: "Almond"})
Species.create({name: "Apple"})
Species.create({name: "Apricot"})
Species.create({name: "Ash"})
Species.create({name: "Aspen"})
Species.create({name: "Birch"})
Species.create({name: "Box Elder"})
Species.create({name: "Bottlebrush"})
Species.create({name: "Buckeye"})
Species.create({name: "Cedar"})
Species.create({name: "Cherry"})
Species.create({name: "Chestnut"})
Species.create({name: "Cottonwood"})
Species.create({name: "Cypress"})
Species.create({name: "Dogwood"})
Species.create({name: "Elm"})
Species.create({name: "Eucalyptus"})
Species.create({name: "Fir"})
Species.create({name: "Ginkgo"})
Species.create({name: "Hackberry"})
Species.create({name: "Hemlock"})
Species.create({name: "Ironwood"})
Species.create({name: "Juniper"})
Species.create({name: "Larch"})
Species.create({name: "Laurel"})
Species.create({name: "Lemon"})
Species.create({name: "Lime"})
Species.create({name: "Locust"})
Species.create({name: "Madrone"})
Species.create({name: "Magnolia"})
Species.create({name: "Maple"})
Species.create({name: "Mesquite"})
Species.create({name: "Oak"})
Species.create({name: "Orange"})
Species.create({name: "Palm"})
Species.create({name: "Peach"})
Species.create({name: "Pecan"})
Species.create({name: "Pine"})
Species.create({name: "Pistache"})
Species.create({name: "Plum"})
Species.create({name: "Monkey Puzzle"})
Species.create({name: "Norfolk Pine"})
Species.create({name: "Redbud"})
Species.create({name: "Redwood"})
Species.create({name: "Sequoia"})
Species.create({name: "Spruce"})
Species.create({name: "Sweet Gum"})
Species.create({name: "Sycamore"})
Species.create({name: "Walnut"})
Species.create({name: "Willow"})
Species.create({name: "Yew"})
Species.create({name: "Zelkova"})